package myapp;

import internalPages.dashBoardPage;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class adddel extends javax.swing.JFrame {

    public adddel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        neo = new javax.swing.JButton();
        chicago = new javax.swing.JButton();
        sicilian = new javax.swing.JButton();
        ny = new javax.swing.JButton();
        cal = new javax.swing.JButton();
        grandma = new javax.swing.JButton();
        salmon = new javax.swing.JButton();
        burnt = new javax.swing.JButton();
        st = new javax.swing.JButton();
        detroit = new javax.swing.JButton();
        crispy = new javax.swing.JButton();
        vegan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn9 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        subtotal = new javax.swing.JTextField();
        tax = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        change = new javax.swing.JTextField();
        payment = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        Pay = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        neo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        neo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/npizza (1).jpg"))); // NOI18N
        neo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neoActionPerformed(evt);
            }
        });
        jPanel1.add(neo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 90));

        chicago.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chicago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cpizza (1).jpg"))); // NOI18N
        chicago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chicagoActionPerformed(evt);
            }
        });
        jPanel1.add(chicago, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 90));

        sicilian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sicilian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/spizza (1).jpg"))); // NOI18N
        sicilian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sicilianActionPerformed(evt);
            }
        });
        jPanel1.add(sicilian, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 90));

        ny.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sss (1).jpg"))); // NOI18N
        ny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyActionPerformed(evt);
            }
        });
        jPanel1.add(ny, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 90));

        cal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/calpizza (1).jpg"))); // NOI18N
        cal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calActionPerformed(evt);
            }
        });
        jPanel1.add(cal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 90));

        grandma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        grandma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/grandma (1).jpg"))); // NOI18N
        grandma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grandmaActionPerformed(evt);
            }
        });
        jPanel1.add(grandma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 120, 90));

        salmon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        salmon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/salmonp (1).jpg"))); // NOI18N
        salmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salmonActionPerformed(evt);
            }
        });
        jPanel1.add(salmon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, 90));

        burnt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        burnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/burnt (1).jpg"))); // NOI18N
        burnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burntActionPerformed(evt);
            }
        });
        jPanel1.add(burnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, 90));

        st.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        st.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/st (1).jpg"))); // NOI18N
        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        jPanel1.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 120, 90));

        detroit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        detroit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dp (1).jpg"))); // NOI18N
        detroit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detroitActionPerformed(evt);
            }
        });
        jPanel1.add(detroit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 90));

        crispy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        crispy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/crispy (1).jpg"))); // NOI18N
        crispy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crispyActionPerformed(evt);
            }
        });
        jPanel1.add(crispy, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, 90));

        vegan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vegan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vegan (1).jpg"))); // NOI18N
        vegan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veganActionPerformed(evt);
            }
        });
        jPanel1.add(vegan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 120, 90));

        jLabel5.setText("Detroit- php 250");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 30));

        jLabel7.setText("Sicilian - php 200");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 120, 30));

        jLabel8.setText("Chicago - php 250");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 30));

        jLabel9.setText("New York - php 220");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 110, 30));

        jLabel10.setText("Neopolitan - php 200");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 130, 30));

        jLabel11.setText("California - php 200");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 30));

        jLabel12.setText("Grandma - php 200");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 30));

        jLabel13.setText("Salmon pizza - php 200");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, 30));

        jLabel14.setText("Burnt - php 200");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 110, 30));

        jLabel15.setText("Vegan - php 200");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 110, 30));

        jLabel16.setText("St. Luis - php 300");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, 30));

        jLabel17.setText("Crispy - php 240");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 550, 400));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 580, 360));

        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 60));

        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 60));

        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 60));

        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 60));

        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 70, 60));

        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 70, 60));

        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 70, 60));

        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 60));

        btn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 60));

        btndot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btndot.setText(".");
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });
        jPanel2.add(btndot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 70, 60));

        btnC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        jPanel2.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 70, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 370));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 210, 400));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Total");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tax");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, 30));

        subtotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 160, 30));

        tax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel7.add(tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 280, 140));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Change");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Payment Method");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        jlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlabel.setText("Cash");
        jPanel8.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 40, 30));

        cash.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel8.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 160, 30));

        change.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel8.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, 30));

        payment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentActionPerformed(evt);
            }
        });
        jPanel8.add(payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 30));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 280, 140));

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel9.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 40));

        Pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Pay.setText("Pay");
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });
        jPanel9.add(Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 40));

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel9.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 40));

        remove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remove.setText("Remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        jPanel9.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 40));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 280, 140));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void ItemCost()
    {
        double sum = 0;
        
        for(int i=0; i<jTable1.getRowCount();i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());          
        }
        subtotal.setText(Double.toString(sum));
        double ctotal = Double.parseDouble(subtotal.getText());
        
        double ctax = (ctotal*3.9)/100;
        String itaxtotal = String.format("₱ %.2f", ctax);
        tax.setText(itaxtotal);
        
        String isubtotal = String.format("₱ %.2f", ctotal);
        subtotal.setText(isubtotal);
        
        String itotal = String.format("₱ %.2f", ctotal + ctax);
        total.setText(itotal);
             
    }
    
    public void Change()
    {
        double sum = 0;
        double itax = 3.9;
        double icash = Double.parseDouble(cash.getText());
        
         for(int i=0; i<jTable1.getRowCount();i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());          
        }
         
         double ctax = (sum*3.9)/100;
         double cchange = (icash - (sum + ctax));
         
         String ChangeGiven = String.format("₱ %.2f", cchange);
         change.setText(ChangeGiven);
    }
    
    
    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
       String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn9.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn9.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
       String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn6.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn6.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn3.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn3.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void neoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neoActionPerformed
       double PriceOfItem = 200;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"neopolitan","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_neoActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        cash.setText("");
        change.setText("");
    }//GEN-LAST:event_btnCActionPerformed

    private void chicagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chicagoActionPerformed
       double PriceOfItem = 250;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Chicago","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_chicagoActionPerformed

    private void sicilianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sicilianActionPerformed
       double PriceOfItem = 200;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Sicilian","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_sicilianActionPerformed

    private void nyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyActionPerformed
       double PriceOfItem = 220;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"New York","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_nyActionPerformed

    private void calActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calActionPerformed
       double PriceOfItem = 200;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"California","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_calActionPerformed

    private void grandmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grandmaActionPerformed
       double PriceOfItem = 200;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Grandma","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_grandmaActionPerformed

    private void salmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salmonActionPerformed
       double PriceOfItem = 200;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Salmon Pizza","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_salmonActionPerformed

    private void burntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burntActionPerformed
       double PriceOfItem = 200;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Burnt","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_burntActionPerformed

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
       double PriceOfItem = 300;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"St. Luis","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_stActionPerformed

    private void detroitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detroitActionPerformed
       double PriceOfItem = 250;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Detroit","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_detroitActionPerformed

    private void crispyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crispyActionPerformed
      double PriceOfItem = 240;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Crispy","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_crispyActionPerformed

    private void veganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veganActionPerformed
      double PriceOfItem = 20;
       
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.addRow(new Object[]{"Vegan","1",PriceOfItem});
       ItemCost();
    }//GEN-LAST:event_veganActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
      String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn1.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn1.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       dashBoardPage dbs = new dashBoardPage();
       dbs.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn7.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn7.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
       String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn8.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn8.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
      String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn4.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn4.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn5.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn5.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
      String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn2.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn2.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
      String Enternumber = cash.getText();
        
        if(Enternumber == "")
        {
            cash.setText(btn0.getText());
        }
        else
        {
            Enternumber = cash.getText() + btn0.getText ();
            cash.setText(Enternumber);
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
      if(! cash.getText(). contains("."))
      {
          cash.setText(cash.getText() + btndot.getText());
      }
    }//GEN-LAST:event_btndotActionPerformed

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
      if(payment.getSelectedItem().equals("Cash"))
      {
          Change();
      }
      else
      {
          change.setText("");
          cash.setText("");
      }
    }//GEN-LAST:event_PayActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      model.setRowCount(0);
      change.setText("");
      tax.setText("");
      total.setText("");
      subtotal.setText("");
      cash.setText("");
      
    }//GEN-LAST:event_resetActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
       MessageFormat header = new MessageFormat("Delivery Order");
       MessageFormat footer = new MessageFormat("Page {0, number,integer}");
       
       try
       {
           jTable1.print(JTable.PrintMode.NORMAL,header,footer);
       }
       
       catch(java.awt.print.PrinterException e)
       {
           System.err.format("No Printer found", e.getMessage());
       }
    }//GEN-LAST:event_printActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       
       int RemoveItem = jTable1.getSelectedRow();
       if(RemoveItem >= 0)
       {
           model.removeRow(RemoveItem);
       }
       
       ItemCost();
    }//GEN-LAST:event_removeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adddel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pay;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btndot;
    private javax.swing.JButton burnt;
    private javax.swing.JButton cal;
    private javax.swing.JTextField cash;
    private javax.swing.JTextField change;
    private javax.swing.JButton chicago;
    private javax.swing.JButton crispy;
    private javax.swing.JButton detroit;
    private javax.swing.JButton grandma;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JButton neo;
    private javax.swing.JButton ny;
    private javax.swing.JComboBox<String> payment;
    private javax.swing.JButton print;
    private javax.swing.JButton remove;
    private javax.swing.JButton reset;
    private javax.swing.JButton salmon;
    private javax.swing.JButton sicilian;
    private javax.swing.JButton st;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField tax;
    private javax.swing.JTextField total;
    private javax.swing.JButton vegan;
    // End of variables declaration//GEN-END:variables
}
